import io
import re
import xml.sax.saxutils
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models.vendor import Vendor, RiskTier
from app.models.document import Document, PolicyVersion
from app.models.risk import RiskAssessment, CategoryScore
from app.schemas.report_schema import (
    VendorSecurityReport,
    ReportVendorInfo,
    ReportExecutiveSummary,
    ReportCategoryScore,
    ReportFinding,
    ReportEvidenceItem,
    ReportPolicySnapshot,
)

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas


def _escape_pdf_text(text: Optional[str]) -> str:
    """Escapes XML/HTML special entities for ReportLab Paragraphs."""
    if not text:
        return ""
    return xml.sax.saxutils.escape(str(text))


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and print total page count and footer."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        # Header rule & title on pages > 1
        if self._pageNumber > 1:
            self.drawString(36, letter[1] - 25, "VendorGuard AI — Executive Security Assessment")
            self.setStrokeColor(colors.HexColor("#cbd5e1"))
            self.setLineWidth(0.5)
            self.line(36, letter[1] - 28, letter[0] - 36, letter[1] - 28)

        # Footer
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(36, 28, letter[0] - 36, 28)
        self.drawString(36, 18, "CONFIDENTIAL • Generated by VendorGuard AI Risk Intelligence")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(letter[0] - 36, 18, page_str)
        self.restoreState()


async def build_vendor_security_report(
    db: AsyncSession,
    vendor_id: str
) -> Optional[VendorSecurityReport]:
    """
    Assembles a complete, structured VendorSecurityReport for a given vendor.
    Loads real documents, versions, latest RiskAssessment, category scores,
    verified findings, evidence citations, and alerts.
    """
    clean_id = str(vendor_id).strip()
    stmt = (
        select(Vendor)
        .options(
            selectinload(Vendor.documents).selectinload(Document.versions),
            selectinload(Vendor.risk_assessments).selectinload(RiskAssessment.category_scores),
            selectinload(Vendor.alerts),
        )
        .where(Vendor.id == clean_id)
    )
    res = await db.execute(stmt)
    vendor = res.scalar_one_or_none()
    if not vendor:
        return None

    now_utc = datetime.now(timezone.utc)

    # 1. Vendor Info
    vendor_status_val = vendor.status.value if hasattr(vendor.status, "value") else str(vendor.status)
    freq_val = vendor.monitoring_frequency.value if hasattr(vendor.monitoring_frequency, "value") else str(vendor.monitoring_frequency)
    risk_tier_val = vendor.risk_tier.value if hasattr(vendor.risk_tier, "value") else str(vendor.risk_tier)

    vendor_info = ReportVendorInfo(
        vendor_id=vendor.id,
        name=vendor.name,
        domain=vendor.domain,
        website_url=vendor.website_url,
        status=vendor_status_val,
        monitoring_frequency=freq_val,
        risk_tier=risk_tier_val,
        current_risk_score=round(float(vendor.current_risk_score), 1),
        last_monitored_at=vendor.last_monitored_at,
    )

    # 2. Risk Assessment Selection
    latest_assessment: Optional[RiskAssessment] = None
    if vendor.risk_assessments:
        sorted_assessments = sorted(
            vendor.risk_assessments,
            key=lambda a: a.assessment_date or a.created_at,
            reverse=True
        )
        latest_assessment = sorted_assessments[0]

    # Check for policy changes
    has_policy_change_alerts = any(
        a.alert_type in ("Policy Change", "Risk Degradation")
        for a in (vendor.alerts or [])
    )
    has_multi_versions = any(
        len(doc.versions) > 1
        for doc in (vendor.documents or [])
    )
    policy_changes_detected = has_policy_change_alerts or has_multi_versions

    doc_count = len(vendor.documents or [])
    policy_posture = f"{doc_count} legal & policy document(s) verified on {vendor.domain}."

    findings: List[ReportFinding] = []
    evidence_items: List[ReportEvidenceItem] = []
    category_scores: List[ReportCategoryScore] = []
    recommendations: List[str] = []
    key_highlights: List[str] = []

    if latest_assessment:
        has_assessment_data = True
        summary_text = latest_assessment.summary or f"Automated risk evaluation completed for {vendor.name}."
        overall_score = round(float(latest_assessment.overall_score), 1)
        overall_tier = latest_assessment.risk_tier

        # Category Scores
        cat_score_map = {cs.category_name: cs for cs in (latest_assessment.category_scores or [])}
        for cat in ["Privacy", "Security", "Compliance", "Legal"]:
            if cat in cat_score_map:
                cs = cat_score_map[cat]
                category_scores.append(ReportCategoryScore(
                    category=cat,
                    score=round(float(cs.score), 1),
                    justification=cs.justification or f"{cat} evaluated via deterministic policy weights."
                ))
            else:
                category_scores.append(ReportCategoryScore(
                    category=cat,
                    score=0.0,
                    justification="No verified findings identified."
                ))

        # Extract findings from category scores (which store full finding details)
        seen_findings = set()
        for cs in (latest_assessment.category_scores or []):
            cs_findings = cs.findings or []
            if isinstance(cs_findings, list):
                for f_data in cs_findings:
                    if isinstance(f_data, dict):
                        f_key = (f_data.get("category", cs.category_name), f_data.get("finding", ""))
                        if f_key not in seen_findings and f_data.get("finding"):
                            seen_findings.add(f_key)
                            findings.append(ReportFinding(
                                category=f_data.get("category", cs.category_name),
                                severity=f_data.get("severity", "Medium"),
                                finding=f_data.get("finding", ""),
                                evidence=f_data.get("evidence"),
                                source_url=f_data.get("source_url"),
                                recommendation=f_data.get("recommendation"),
                                is_verified=bool(f_data.get("is_verified", True)),
                            ))

        # Fallback to key_findings if category scores didn't contain finding list
        if not findings and latest_assessment.key_findings and isinstance(latest_assessment.key_findings, list):
            for f_data in latest_assessment.key_findings:
                if isinstance(f_data, dict) and f_data.get("finding"):
                    findings.append(ReportFinding(
                        category=f_data.get("category", "General"),
                        severity=f_data.get("severity", "Medium"),
                        finding=f_data.get("finding", ""),
                        evidence=f_data.get("evidence"),
                        source_url=f_data.get("source_url"),
                        recommendation=f_data.get("recommendation"),
                        is_verified=bool(f_data.get("is_verified", True)),
                    ))

        # Highlights from top severity findings
        high_critical = [f.finding for f in findings if f.severity in ("Critical", "High")]
        key_highlights = high_critical[:3] if high_critical else [f.finding for f in findings[:2]]

        # Evidence / Citations
        seen_quotes = set()
        # From citations list
        if latest_assessment.citations and isinstance(latest_assessment.citations, list):
            for cit in latest_assessment.citations:
                if isinstance(cit, dict):
                    quote = cit.get("snippet") or cit.get("evidence") or ""
                    if quote and quote not in seen_quotes:
                        seen_quotes.add(quote)
                        evidence_items.append(ReportEvidenceItem(
                            category=cit.get("category", "General"),
                            document_type=cit.get("document_type", "Policy Document"),
                            title=cit.get("title", "Policy Document"),
                            source_url=cit.get("source_url", vendor.website_url),
                            quote=quote,
                            is_verified=True,
                        ))

        # From findings evidence
        for f in findings:
            if f.evidence and f.evidence not in seen_quotes:
                seen_quotes.add(f.evidence)
                evidence_items.append(ReportEvidenceItem(
                    category=f.category,
                    document_type="Policy Document",
                    title=f.category + " Policy",
                    source_url=f.source_url or vendor.website_url,
                    quote=f.evidence,
                    is_verified=f.is_verified,
                ))

        # Recommendations
        for f in findings:
            if f.recommendation and f.recommendation not in recommendations:
                recommendations.append(f.recommendation)

        if not recommendations:
            recommendations.append(f"Maintain {freq_val.lower()} continuous monitoring to identify subsequent policy revisions.")
            recommendations.append("Review vendor SOC 2 Type II or ISO 27001 audit certifications during renewal.")

    else:
        # Vendor discovered, but not yet analyzed
        has_assessment_data = False
        summary_text = (
            f"No formal risk assessment has been executed yet for {vendor.name}. "
            f"{doc_count} legal & policy document(s) have been discovered and cataloged, "
            f"but AI risk extraction has not been initiated."
        )
        overall_score = round(float(vendor.current_risk_score), 1)
        overall_tier = risk_tier_val

        category_scores = [
            ReportCategoryScore(category=cat, score=0.0, justification="Assessment pending.")
            for cat in ["Privacy", "Security", "Compliance", "Legal"]
        ]
        recommendations = [
            f"Initiate an AI Risk Assessment or Multi-Agent Workflow for {vendor.name} to extract grounded findings.",
            f"Verify all discovered legal documents on {vendor.domain}.",
        ]

    executive_summary = ReportExecutiveSummary(
        summary_text=summary_text,
        overall_risk_tier=overall_tier,
        overall_score=overall_score,
        policy_posture=policy_posture,
        policy_changes_detected=policy_changes_detected,
        key_highlights=key_highlights,
    )

    # 3. Policy Snapshots
    policy_snapshots: List[ReportPolicySnapshot] = []
    for doc in (vendor.documents or []):
        latest_version = doc.versions[0] if doc.versions else None
        policy_snapshots.append(ReportPolicySnapshot(
            document_id=doc.id,
            document_type=doc.document_type,
            title=doc.title,
            url=doc.url,
            current_version_hash=doc.current_version_hash or (latest_version.content_hash if latest_version else None),
            version_number=latest_version.version_number if latest_version else 1,
            last_crawled_at=doc.last_crawled_at or (latest_version.crawled_at if latest_version else None),
            change_summary=latest_version.change_summary if latest_version else None,
        ))

    return VendorSecurityReport(
        vendor=vendor_info,
        executive_summary=executive_summary,
        risk_overview=category_scores,
        findings=findings,
        evidence=evidence_items,
        recommendations=recommendations,
        policy_snapshots=policy_snapshots,
        has_assessment_data=has_assessment_data,
        generated_at=now_utc,
    )


def generate_markdown_report(report: VendorSecurityReport) -> str:
    """Renders a comprehensive, GitHub-Flavored Markdown Executive Security Report."""
    v = report.vendor
    s = report.executive_summary
    gen_time_str = report.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        f"# Executive Security Assessment Report: {v.name}",
        "",
        f"> **Vendor Risk Intelligence Brief** — Generated on {gen_time_str} by VendorGuard AI",
        "",
        "---",
        "",
        "## 1. Vendor Profile & Posture",
        "",
        f"- **Vendor Name**: {v.name}",
        f"- **Primary Domain**: `{v.domain}`",
        f"- **Website URL**: [{v.website_url}]({v.website_url})",
        f"- **Monitoring Status**: `{v.status}` ({v.monitoring_frequency} Interval)",
        f"- **Last Monitored**: {v.last_monitored_at.strftime('%Y-%m-%d %H:%M:%S UTC') if v.last_monitored_at else 'Not yet monitored'}",
        f"- **Overall Risk Score**: **{v.current_risk_score:.1f} / 100**",
        f"- **Risk Tier**: **`{v.risk_tier}`**",
        "",
        "---",
        "",
        "## 2. Executive Summary",
        "",
        s.summary_text,
        "",
        f"- **Policy Posture**: {s.policy_posture}",
        f"- **Policy Changes Detected**: {'Yes (Recent changes tracked in audit history)' if s.policy_changes_detected else 'No (Policy hashes unchanged since initial crawl)'}",
    ]

    if s.key_highlights:
        lines.append("")
        lines.append("**Key Risk Highlights:**")
        for h in s.key_highlights:
            lines.append(f"- {h}")

    lines.extend([
        "",
        "---",
        "",
        "## 3. Category Risk Overview",
        "",
        "| Category | Risk Score (0-100) | Weight | Justification |",
        "| :--- | :--- | :--- | :--- |",
    ])

    weights = {"Privacy": "30%", "Security": "30%", "Compliance": "20%", "Legal": "20%"}
    for cat in report.risk_overview:
        w = weights.get(cat.category, "20%")
        lines.append(f"| **{cat.category}** | {cat.score:.1f} | {w} | {cat.justification or 'Evaluated'} |")

    lines.extend([
        "",
        "---",
        "",
        "## 4. Key Risk Findings",
        "",
    ])

    if report.findings:
        for idx, f in enumerate(report.findings, start=1):
            verified_badge = "✓ Verified" if f.is_verified else "⚠ Unverified"
            lines.append(f"### {idx}. [{f.severity.upper()}] {f.finding}")
            lines.append(f"- **Category**: {f.category}")
            lines.append(f"- **Verification Status**: {verified_badge}")
            if f.recommendation:
                lines.append(f"- **Mitigation Action**: {f.recommendation}")
            if f.evidence:
                lines.append(f"- **Policy Quote**: \"_{f.evidence.strip()}_\"")
            if f.source_url:
                lines.append(f"- **Source Reference**: [{f.source_url}]({f.source_url})")
            lines.append("")
    else:
        lines.append("_No verified risk findings recorded for this vendor._")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## 5. Verified Policy Evidence",
        "",
    ])

    if report.evidence:
        for idx, ev in enumerate(report.evidence, start=1):
            lines.append(f"**Evidence #{idx} — {ev.category} ({ev.document_type})**")
            lines.append(f"> \"{ev.quote.strip()}\"")
            lines.append(f"> ")
            lines.append(f"> — *Source*: [{ev.title}]({ev.source_url})")
            lines.append("")
    else:
        lines.append("_No verified evidence quotes currently on record for this vendor._")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## 6. Actionable Risk Mitigation Recommendations",
        "",
    ])

    if report.recommendations:
        for r in report.recommendations:
            lines.append(f"- [ ] {r}")
    else:
        lines.append("- [ ] Continue continuous monitoring for policy revisions.")

    lines.extend([
        "",
        "---",
        "",
        "## 7. Policy Snapshots & Hash Versioning",
        "",
        "| Document Type | Title | URL | SHA-256 Version Hash | Version | Last Crawled |",
        "| :--- | :--- | :--- | :--- | :--- | :--- |",
    ])

    if report.policy_snapshots:
        for ps in report.policy_snapshots:
            hash_snippet = ps.current_version_hash[:16] + "..." if ps.current_version_hash else "None"
            last_crawled_str = ps.last_crawled_at.strftime("%Y-%m-%d") if ps.last_crawled_at else "Never"
            lines.append(
                f"| {ps.document_type} | {ps.title} | [{ps.url}]({ps.url}) | `{hash_snippet}` | v{ps.version_number} | {last_crawled_str} |"
            )
    else:
        lines.append("| — | No documents discovered | — | — | — | — |")

    lines.extend([
        "",
        "---",
        "*Confidential Security Report — Generated automatically by VendorGuard AI.*",
    ])

    return "\n".join(lines)


def generate_pdf_report(report: VendorSecurityReport) -> bytes:
    """
    Renders an executive-grade PDF security assessment report using ReportLab.
    Includes custom color-coded risk tiers, category score breakdown table,
    finding callouts, verified evidence quotes, and policy snapshot versioning.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()

    # Custom Color Palette
    primary_color = colors.HexColor("#0f172a")    # Slate 900
    accent_color = colors.HexColor("#0284c7")     # Sky blue
    muted_color = colors.HexColor("#64748b")      # Slate 500
    border_color = colors.HexColor("#e2e8f0")     # Slate 200
    bg_light = colors.HexColor("#f8fafc")         # Slate 50

    tier_colors = {
        "Low": colors.HexColor("#10b981"),        # Emerald 500
        "Medium": colors.HexColor("#f59e0b"),     # Amber 500
        "High": colors.HexColor("#f97316"),       # Orange 500
        "Critical": colors.HexColor("#ef4444"),   # Red 500
    }
    tier_bg_colors = {
        "Low": colors.HexColor("#ecfdf5"),
        "Medium": colors.HexColor("#fffbeb"),
        "High": colors.HexColor("#fff7ed"),
        "Critical": colors.HexColor("#fef2f2"),
    }

    # Typography Styles
    style_title = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=primary_color,
        spaceAfter=4,
    )
    style_subtitle = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=muted_color,
        spaceAfter=12,
    )
    style_h2 = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=primary_color,
        spaceBefore=12,
        spaceAfter=6,
    )
    style_body = ParagraphStyle(
        "BodyRegular",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#1e293b"),
        spaceAfter=6,
    )
    style_body_bold = ParagraphStyle(
        "BodyBold",
        parent=style_body,
        fontName="Helvetica-Bold",
    )
    style_quote = ParagraphStyle(
        "QuoteText",
        parent=styles["Italic"],
        fontName="Helvetica-Oblique",
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor("#334155"),
    )
    style_meta = ParagraphStyle(
        "MetaText",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        textColor=muted_color,
    )
    style_table_cell = ParagraphStyle(
        "TableCell",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#1e293b"),
    )
    style_table_header = ParagraphStyle(
        "TableHeader",
        parent=style_table_cell,
        fontName="Helvetica-Bold",
        textColor=primary_color,
    )

    story = []

    v = report.vendor
    s = report.executive_summary
    tier_col = tier_colors.get(v.risk_tier, primary_color)
    tier_bg = tier_bg_colors.get(v.risk_tier, bg_light)

    # 1. Header Banner Table
    banner_left = [
        Paragraph("<b>VENDORGUARD AI</b> — EXECUTIVE RISK INTELLIGENCE", style_subtitle),
        Paragraph(f"<b>Security Assessment: {_escape_pdf_text(v.name)}</b>", style_title),
        Paragraph(
            f"<b>Domain:</b> {_escape_pdf_text(v.domain)} &nbsp;|&nbsp; "
            f"<b>Website:</b> {_escape_pdf_text(v.website_url)} &nbsp;|&nbsp; "
            f"<b>Generated:</b> {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
            style_meta,
        ),
    ]

    banner_right = [
        Paragraph(
            f"<para align='center'><font size='8' color='{tier_col.hexval()}'><b>RISK TIER</b></font><br/>"
            f"<font size='16' color='{tier_col.hexval()}'><b>{v.risk_tier}</b></font><br/>"
            f"<font size='8' color='#64748b'>Score: <b>{v.current_risk_score:.1f}/100</b></font></para>",
            style_body,
        )
    ]

    header_table = Table(
        [[banner_left, banner_right]],
        colWidths=[420, 120],
    )
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BACKGROUND", (1, 0), (1, 0), tier_bg),
        ("BOX", (1, 0), (1, 0), 1, tier_col),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (1, 0), (1, 0), 8),
        ("RIGHTPADDING", (1, 0), (1, 0), 8),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1, color=border_color, spaceBefore=0, spaceAfter=8))

    # 2. Executive Summary
    story.append(Paragraph("1. Executive Summary", style_h2))
    story.append(Paragraph(_escape_pdf_text(s.summary_text), style_body))

    # Posture Summary Row
    changes_status = "Detected & Tracked" if s.policy_changes_detected else "No Changes (Clean Hashes)"
    posture_text = (
        f"<b>Policy Posture:</b> {_escape_pdf_text(s.policy_posture)} &nbsp;|&nbsp; "
        f"<b>Continuous Monitoring:</b> {v.monitoring_frequency} Interval &nbsp;|&nbsp; "
        f"<b>Delta Hash Status:</b> {changes_status}"
    )
    story.append(Paragraph(posture_text, style_meta))

    if s.key_highlights:
        story.append(Spacer(1, 4))
        for h in s.key_highlights:
            story.append(Paragraph(f"• <b>Key Observation:</b> {_escape_pdf_text(h)}", style_body))

    story.append(Spacer(1, 8))

    # 3. Category Risk Overview Table
    story.append(Paragraph("2. Category Risk Breakdown", style_h2))

    cat_table_data = [[
        Paragraph("Risk Dimension", style_table_header),
        Paragraph("Score", style_table_header),
        Paragraph("Weight", style_table_header),
        Paragraph("Assessment Justification", style_table_header),
    ]]

    weights_map = {"Privacy": "30%", "Security": "30%", "Compliance": "20%", "Legal": "20%"}
    for cat in report.risk_overview:
        score_val = cat.score
        score_color = "#ef4444" if score_val >= 75 else "#f97316" if score_val >= 50 else "#f59e0b" if score_val >= 25 else "#10b981"
        cat_table_data.append([
            Paragraph(f"<b>{cat.category}</b>", style_table_cell),
            Paragraph(f"<font color='{score_color}'><b>{score_val:.1f}</b></font>", style_table_cell),
            Paragraph(weights_map.get(cat.category, "20%"), style_table_cell),
            Paragraph(_escape_pdf_text(cat.justification or "Evaluated"), style_table_cell),
        ])

    cat_table = Table(cat_table_data, colWidths=[100, 60, 60, 320])
    cat_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), bg_light),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("GRID", (0, 0), (-1, -1), 0.5, border_color),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(cat_table)
    story.append(Spacer(1, 10))

    # 4. Key Findings
    story.append(Paragraph("3. Key Risk Findings", style_h2))
    if report.findings:
        for idx, f in enumerate(report.findings, start=1):
            sev_color = tier_colors.get(f.severity, primary_color)
            f_box = [
                Paragraph(
                    f"<b>Finding #{idx}</b> &nbsp;|&nbsp; "
                    f"<font color='{sev_color.hexval()}'><b>[{f.severity.upper()}]</b></font> &nbsp;|&nbsp; "
                    f"<b>Category:</b> {f.category} &nbsp;|&nbsp; "
                    f"<font color='#059669'><b>{'Verified Quote' if f.is_verified else 'Unverified'}</b></font>",
                    style_table_header,
                ),
                Paragraph(_escape_pdf_text(f.finding), style_body),
            ]
            if f.recommendation:
                f_box.append(Paragraph(f"<b>Recommendation:</b> {_escape_pdf_text(f.recommendation)}", style_body))
            if f.evidence:
                f_box.append(Paragraph(
                    f"<i>Evidence Excerpt:</i> \"{_escape_pdf_text(f.evidence[:350] + ('...' if len(f.evidence) > 350 else ''))}\"",
                    style_quote,
                ))
            if f.source_url:
                f_box.append(Paragraph(f"<i>Source Policy:</i> {_escape_pdf_text(f.source_url)}", style_meta))

            f_table = Table([[f_box]], colWidths=[540])
            f_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), bg_light),
                ("BOX", (0, 0), (-1, -1), 0.5, border_color),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(f_table)
            story.append(Spacer(1, 6))
    else:
        story.append(Paragraph("<i>No verified risk findings identified for this vendor.</i>", style_body))

    story.append(Spacer(1, 6))

    # 5. Verified Policy Evidence Quotes
    story.append(Paragraph("4. Verified Policy Excerpts & Evidence", style_h2))
    if report.evidence:
        for idx, ev in enumerate(report.evidence[:8], start=1):  # Include up to 8 core excerpts
            snippet_text = ev.quote[:400] + ("..." if len(ev.quote) > 400 else "")
            ev_box = [
                Paragraph(
                    f"<b>Excerpt #{idx}</b> — {_escape_pdf_text(ev.category)} ({_escape_pdf_text(ev.document_type)})",
                    style_body_bold,
                ),
                Paragraph(f"\"{_escape_pdf_text(snippet_text)}\"", style_quote),
                Paragraph(
                    f"<b>Document:</b> {_escape_pdf_text(ev.title)} &nbsp;|&nbsp; <b>URL:</b> {_escape_pdf_text(ev.source_url)}",
                    style_meta,
                ),
            ]
            ev_table = Table([[ev_box]], colWidths=[540])
            ev_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f1f5f9")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(ev_table)
            story.append(Spacer(1, 5))
    else:
        story.append(Paragraph("<i>No verified policy quotations on record.</i>", style_body))

    story.append(Spacer(1, 6))

    # 6. Actionable Recommendations
    story.append(Paragraph("5. Recommended Risk Actions", style_h2))
    if report.recommendations:
        for rec in report.recommendations:
            story.append(Paragraph(f"• {_escape_pdf_text(rec)}", style_body))
    else:
        story.append(Paragraph("• Continue scheduled monitoring cycle.", style_body))

    story.append(Spacer(1, 6))

    # 7. Discovered Policy Documents Table
    story.append(Paragraph("6. Policy Document Snapshots & SHA-256 Hashes", style_h2))
    doc_table_data = [[
        Paragraph("Type", style_table_header),
        Paragraph("Title", style_table_header),
        Paragraph("Version", style_table_header),
        Paragraph("SHA-256 Hash Digest", style_table_header),
        Paragraph("Crawled", style_table_header),
    ]]

    for ps in report.policy_snapshots:
        hash_snippet = ps.current_version_hash[:16] + "..." if ps.current_version_hash else "None"
        crawled_date = ps.last_crawled_at.strftime("%Y-%m-%d") if ps.last_crawled_at else "Never"
        doc_table_data.append([
            Paragraph(_escape_pdf_text(ps.document_type), style_table_cell),
            Paragraph(_escape_pdf_text(ps.title[:30]), style_table_cell),
            Paragraph(f"v{ps.version_number}", style_table_cell),
            Paragraph(f"<font name='Courier'>{hash_snippet}</font>", style_table_cell),
            Paragraph(crawled_date, style_table_cell),
        ])

    doc_table = Table(doc_table_data, colWidths=[100, 140, 50, 160, 90])
    doc_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), bg_light),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("GRID", (0, 0), (-1, -1), 0.5, border_color),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(doc_table)

    # Build PDF with dynamic footer
    doc.build(story, canvasmaker=NumberedCanvas)
    return buf.getvalue()
